---
title: "week7HW"
author: "Kyle Bosworth"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
  pdf_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 10, 
                      fig.height = 6, 
                      out.width = "100%", 
                      fig.retina = 3,
                      fig.align = "center",
                      fig.path = here::here("Bosworth","week7", "outputs", "/"))
```

### Load libraries
```{r}
library(here)
library(tidyverse)
library(maps)
library(mapdata)
library(mapproj)
library(ggspatial)
library(data.table)
library(ggmap)
library(ggspatial)
```
### Read in Data
```{r}
BFdata <- read.csv(here("week7", "data", "bigfoot.csv")) %>%
  filter(season != "Unknown")
glimpse(BFdata)
```

Get map and define boundaries
```{r}
#Defines the request area for North America map tiles
north_america_bbox<-c(left = -180, bottom = 15, right = -50, top = 75)

#Get map
north_america_map <- get_stadiamap(north_america_bbox, zoom = 4, maptype = "stamen_terrain")

```

# Bigfoot Sightings 
```{r}
ggmap(north_america_map) +
  geom_point(data = BFdata, aes(x = longitude, 
                                y = latitude,
                                color = season), alpha = 0.7, size = 2)+
  scale_color_viridis_d(name = "Season")+
  labs(title = "Bigfoot Sighting in North America",
       subtitle = "Colored by Season",
       x = "Longitude",
       Y = "Latitude")+
  theme_minimal()+
  theme(legend.position = "right",
        plot.title = element_text(size = 16,
                                  face = "bold"),
        plot.subtitle = element_text(size = 12,
                                     face = "italic"),
        panel.grid.major = element_line(color = "white", 
                                        linetype = "dashed"),
        panel.border = element_rect(color = "black",
                                    fill = NA, 
                                    size = 1),
    axis.ticks = element_line(size = 0.5), #adding lat and long ticks on the scales
    axis.ticks.length = unit(0.25, "cm")) +
  coord_cartesian(xlim = c(-180, -50), 
                  ylim = c(15, 75), expand = FALSE)
```

