---
title: "week7classworkb"
author: "Kyle Bosworth"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 10, 
                      fig.height = 6, 
                      out.width = "100%", 
                      fig.retina = 3,
                      fig.align = "center",
                      fi.path = "../outputs/")
```

### Load libraries
```{r}
library(tidyverse)
library(here)
library(maps)
# maps The {maps} package is a combination of functions that pair well with ggplot and base layers for maps (i.e. polygons of regions of interest).

## map_data("location") is the function used to pull out whatever base layer that you want.

library(mapdata)
library(mapproj)
library(kableExtra)
library(prettydoc)
library(ggspatial)
library(data.table)
library(ggmap)


ggmap::register_google(key = "AIzaSyDFEiZfRlGQ6VKco6XljqHYg1iuHZBSm3c")
register_stadiamaps("7d632143-15b1-4847-925d-04842047a2e9", write = TRUE)

```

### Read in data
```{r}
ChemData<-read.csv(here("week7","data","chemicaldata_maunalua.csv"))
glimpse(ChemData)
```

### Get basemaps from ggmap
```{r}
# get_map() is the function to get a basemap from google maps.

#location as a string:
Oahu<-get_map("oahu")

ggmap(Oahu)

#you can also pu in lat and long coordinates to get a basemap.
## get coordinates for Wailupe on Oahu

#make a data frame of lat and long coordinates
WP<-data.frame(lon = -157.7621, lat = 21.27427)

#grab base layer
Map1<-get_map(WP)

#plot it
ggmap(Map1)

#ZOOM, the zoom argument, an integer from 3 to 20 specifying how large the patial extent should be around the center, with 3 being the continent level and 20 being roughly the single building level. 
Map1<-get_map(WP,zoom = 17)
ggmap(Map1)

#change the map type!
Map1<-get_map(WP,
              zoom = 17,
              maptype = "satellite")
ggmap(Map1)

# You can use the ggmap base layer in any ggplot
Map1<-get_map(WP,zoom = 17,maptype = "satellite")
ggmap(Map1)+
  geom_point(data = ChemData,
             aes(x = Long,
                 y = Lat,
                 color = Salinity),
             size = 4) +
  scale_color_viridis_c()

# Now letʻs ADD a Scale Bar
Map1<-get_map(WP,zoom = 17,maptype = "satellite")
ggmap(Map1)+
  geom_point(data = ChemData, 
             aes(x = Long, y = Lat, color = Salinity), 
             size = 4) + 
  scale_color_viridis_c()+
  annotation_scale( bar_cols = c("yellow", "white"),
                    location = "bl")+ # put the bar on the bottom left and make the colors yellow and white
  annotation_north_arrow(location = "tl")+ # add a north arrow
  coord_sf(crs = 4326) # for the scale bar to work it needs to be in this coordinate system - this is a typical coordinate reference system for a GPS (WGS84)


```
Awsome r pach=kage
```{r}
install.packages("emojifont")
```

