---
title: "week7classwork"
author: "Kyle Bosworth"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fi.path = "../outputs/")

```

### Load libraries
```{r}
library(tidyverse)
library(here)
library(maps)
# maps The {maps} package is a combination of functions that pair well with ggplot and base layers for maps (i.e. polygons of regions of interest).

## map_data("location") is the function used to pull out whatever base layer that you want.

library(mapdata)
library(mapproj)
library(kableExtra)
library(prettydoc)
```

```{r}
# Read in data on population in California by county
popdata<-read.csv(here("week7","data","CApopdata.csv"))
#read in data on number of seastars at different field sites
stars<-read.csv(here("week7","data","stars.csv"))

#maps package
world<-map_data("world")
counties<-map_data("county")
head(counties)


#Structure of the data

### Long is longitude. Things to the west of the prime meridian are negative.

### Lat is latitude.

### Order. This just shows in which order ggplot should “connect the dots”

### Region and subregion tell what region or subregion a set of points surrounds.

### Group. This is very important! ggplot2’s functions can take a group argument which controls (amongst other things) whether adjacent points should be connected by lines. If they are in the same group, then they get connected, but if they are in different groups then they don’t. Essentially, having to points in different groups means that ggplot “lifts the pen” when going between them.
```

Make a Map of the world
```{r}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long,
                   y = lat,
                   group = group, 
                   fill = region),
               color = "black")+
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue"))+
  coord_map(projection = "sinusoidal",
            xlim = c(-180,180))
```
Letʻs make a map of just California
```{r}
# get data for states
states<-map_data("state")
head(states)
# Use the states dataset
CA_data<-states %>%
  filter(region == "california")

ggplot()+
geom_polygon(data = CA_data, 
               aes(x = long,
                   y = lat,
                   group = group, 
                   fill = region),
               color = "black")+
  coord_map()
```

Adding multiple layers of data
```{r}
# Look at the county data
head(counties)[1:3,] # only showing the first 3 rows for space
# Look at the county data
head(popdata)

CApop_county<-popdata %>%
  select("subregion" = County, Population) %>% # rename the county col
  inner_join(counties) %>%
  filter(region == "california") # some counties have the same names in other state
```

Map of CA population by county
```{r}
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")
```

Add a layer of points
```{r}
head(stars)

ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites 
             aes(x = long, 
                 y = lat,
                 size = star_no))+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")
labs(size = "# stars/m2") #make a better legend label
ggsave(here("week7","outputs","CApop.pdf"))
```
Awsome R Package
```{r}
remotes::install_github("R-CoderDotCom/ggdogs@main")
library(ggdogs)
ggplot(mtcars) +
  geom_dog(aes(mpg, wt), dog = "pug", size = 5)

```

