---
title: "week8classworkaa"
author: "Kyle Bosworth"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fi.path = "../outputs/")
ggmap::register_google(key = "AIzaSyDFEiZfRlGQ6VKco6XljqHYg1iuHZBSm3c")
register_stadiamaps ("7d632143-15b1-4847-925d-04842047a2e9", write = TRUE)
```


### Load Libraries
```{r}
library(here)
library(tidyverse)
library(maps)
library(mapdata)
library(mapproj)
library(ggspatial)
library(data.table)
library(ggmap)
library(ggspatial)

library(tidytext)
library(wordcloud2)
library(janeaustenr)

library(patchwork)
library(ggrepel)
library(gganimate)
library(magick)
library(palmerpenguins)

```

Patchwork, easily bring your plots together.

```{r}
# Letʻs srtart with two simple plots from the PP data set
# plot 1
p1<-penguins %>%
  ggplot(aes(x = body_mass_g, 
             y = bill_length_mm, 
             color = species))+
  geom_point()
p1
p2<-penguins %>%
  ggplot(aes(x = sex, 
             y = body_mass_g, 
             color = species))+
  geom_jitter(width = 0.2)
p2
#bring them together using:
p1+p2


#Group the legends:

p1+p2 +
  plot_layout(guides = 'collect')
plot_annotation(tag_levels = 'A') #add labels A,B


#plot one ontop of the other: 
p1/p2 +
  plot_layout(guides = 'collect')+
  plot_annotation(tag_levels = 'A')
```
ggrepel, easy and clear labels for plots
```{r}
#Use the mtcars dataset that comes with it. It is data on cars.

View(mtcars)

ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text() + # creates a text label
  geom_point(color = 'red')


# Repel the labels.
ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text_repel() + # repel them
  geom_point(color = 'red')


# Use the label function.
ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_label_repel() + # repel them
  geom_point(color = 'red')
```
gganimate, make your figure an animation!
```{r}
# Let's go back to our penguin plot, but animate the figure by year. Our static plot.
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   )+
  ease_aes("bounce-in-out") +
  labs(title = 'Year: {closest_state}') + #add a transition title
  anim_save(here("week8","outputs","mypengiungif.gif")) # save it as a GIF
```
magick, advanced image processing
```{r}
# Put a penguin in it.
# Read in an image of a pengiun (can be on your computer or the internet).

penguin<-image_read("https://pngimg.com/uploads/penguin/pinguin_PNG9.png")
penguin

# to put it on a ploit you first need to save =you plot as the image.:
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point()
  ggsave(here("week8","outputs","penguinplot.png"))

# read in the plot as a magick image and make a composite plot:  
penplot<-image_read(here("week8","outputs","penguinplot.png"))
out <- image_composite(penplot, penguin, offset = "+70+30")
out

# Read in a penguin gif
pengif<-image_read("https://media3.giphy.com/media/H4uE6w9G1uK4M/giphy.gif")
outgif <- image_composite(penplot, pengif, gravity = "center")
animation <- image_animate(outgif, fps = 10, optimize = TRUE)
animation

```

